image: node

stages:
  - test

before_script:
  - npm i --silent

build:
  stage: test
  script:
    - yarn bundle

test:
  stage: test
  script:
    - yarn test

lint:
  stage: test
  script:
    - yarn lint

flow:
  stage: test
  script:
    - yarn flow check
