image: node:9

stages:
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

before_script:
  - yarn || true # Don't blow up when 'yarn' doesn't exist

install:
  stage: build
  script:
    - echo 🐖
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

storybook:
  stage: build
  script:
    - yarn storybook:build
  artifacts:
    paths:
      - dist-storybook/

release:
  stage: release
  script:
    - echo "Upload to S3"
