image: node

stages:
  - install
  - build

#before_script:
# - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

install:
  stage: install
  script:
    - yarn
  artifacts:
    paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn bundle
  artifacts:
    paths:
    - data/
    - dist/

test:
  stage: build
  script:
    - yarn test

lint:
  stage: build
  script:
    - yarn lint

madge:
  stage: build
  script:
    - yarn madge

flow:
  stage: build
  script:
    - yarn flow check
