image: node

stages:
  - install
  - build

#before_script:
# - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

install:
  stage: install
  script:
    - yarn
  artifacts:
    paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn bundle
  dependencies:
    - install
  artifacts:
    paths:
    - data/
    - dist/

test:
  stage: build
  script:
    - yarn test
  dependencies:
    - install

lint:
  stage: build
  script:
    - yarn lint
  dependencies:
    - install

madge:
  stage: build
  script:
    - yarn madge
  dependencies:
    - install

flow:
  stage: build
  script:
    - yarn flow check
  dependencies:
    - install
