image: node:carbon

stages:
  - test

before_script:
  - npm i --silent

build:
  stage: test
  script:
    - npm run bundle

test:
  stage: test
  script:
    - npm test

lint:
  stage: test
  script:
    - npm run lint

flow:
  stage: test
  script:
    - npm run flow:check
